namespace Exception_Async_Await_Pj.ExceptionClasses
{
    internal class Divide
    {
        public double Divide2Numbs(int n0, int n1)
        {
            dynamic rz = n0 / n1;
            return rz;
        }
    }
}
